version: '3.8'

services:
  aegis:
    build: .
    container_name: aegis_dev
    # Maps your current Windows folder (.) to /app inside Docker
    volumes:
      - .:/app
      - .cre-config:/root/.cre

    # Uses your .env file for secrets
    env_file:
      - .env
    # Enables interactive terminal
    tty: true
